### PR TITLE
Fix html reporter toolbar bug

### LINKED ISSUE #732: 1.17.0 & phantomjs
Heads up, I'm seeing tests hang when using phantomjs as `phantomjs test.js`. It looks like things are getting exported correctly and the `QUnit.load()` is getting called. I'll know more this evening when I dig-in fully.

### PR DESCRIPTION
**Pull request by jzaefferer**
Creating a PR for @leobalter's branch, to have a proper reference when merging.

Fixes #732
Closes #731

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -96,7 +96,9 @@ grunt.initConfig({
 			"test/autostart.html",
 			"test/startError.html",
 			"test/logs.html",
-			"test/setTimeout.html"
+			"test/setTimeout.html",
+			"test/reporter-html-legacy-markup.html",
+			"test/reporter-html-no-qunit-element.html"
```
Comment (jzaefferer) [inline Gruntfile.js]: Without the reporter fix below, this test just times out. Let's try to improve this to produce a useful failure.

**Comment by jzaefferer** [comment]
I think its fine to run those two new pages only through grunt/phantom. No need to blow up the runtime for browserstack-runner even further.

@leobalter can you look into producing a "proper failure", instead of the timeout?

File: Gruntfile.js (hunk 1 above)
Comment (jonbretman) [inline Gruntfile.js]: Yeh I noticed this too, tried to make it fail with an error but got lost :( A proper failure would be better than timing out. I assume it's because the error is being suppressed somewhere?

**Comment by leobalter** [comment]
the better failure I could produce was this last commit, setting a timeout in order to print something at the PhantomJS reporter.

Throwing an error, etc, doesn't print anything there.

**Comment by jzaefferer** [comment]
Good enough, I guess. Can you squash and merge?
